### PR TITLE
Changed "completed" chip

### LINKED ISSUE #1413: Portal events page: Completed events
**Describe the bug**
Portal events show completed even when the event itself is not marked as completed in the db. I think its just time based

Image

### PR DESCRIPTION
**Pull request by emmr253**
## Description

Please include a summary of the changes made, and the related issue.
List any dependencies that are required for this change.

Closes #1413 

### Type of change
- [V] Bug fix (non-breaking change which fixes an issue)

## Screenshots
Screenshot 2025-11-16 185712

## Checklist
- [ ] My code follows the style guidelines of this project
- [V] I have performed a self-review of my code
- [V] My changes generate no new warnings

### CODE REVIEW

File: apps/portal/src/app/[locale]/events/components/event-list-item.tsx [hunk 1]
```diff
@@ -26,29 +26,17 @@ export const EventListItem: React.FC<EventListItemProps> = ({ event, variant = '
   const tEvents = useTranslations('pages.index.events');
 
   const getStatusChip = () => {
-    switch (variant) {
-      case 'active':
-        return <LiveIcon />;
```
Comment (johnmeshulam) [inline apps/portal/src/app/[locale]/events/components/event-list-item.tsx]: We still want the live icon for events that are active but not completed

File: apps/backend/src/routers/portal/events/util.ts [hunk 2]
```diff
@@ -38,7 +38,7 @@ export const makePortalEventSummaryResponse = (event: DbEventSummary): EventSumm
     ? 'upcoming'
     : eventDate.isBefore(today)
       ? 'past'
-      : 'active';
```
Comment (johnmeshulam) [inline apps/backend/src/routers/portal/events/util.ts]: Why did we remove the ;
