### PR TITLE
Lead Mentor Award missing from presentation

### LINKED ISSUE #1965: Lead Mentor Award missing from presentation
**Describe the bug**
In the slides-builder file we seem to skip lead mentor (and possibly also volunteer of the year).

**To Reproduce**
1. Go to awards presentation
2. See missing awards

**Expected behavior**
Personal awards also included in presentation

### PR DESCRIPTION
**Pull request by CoolGame8**
closes #1965 

maybe need to do smothing with the undefined 
Screenshot 2026-02-23 at 18 41 01

### CODE REVIEW

File: apps/frontend/src/app/[locale]/lems/(volunteer)/(dashboard)/scorekeeper/components/awards-presentation/awards-presentation-wrapper.tsx [hunk 1]
```diff
@@ -13,32 +13,55 @@ export function AwardsPresentationWrapper() {
...
-            city: teamData.city || '',
-            affiliation: teamData.affiliation || ''
+          // Ensure team data is valid before accessing properties
+          if (!teamData || !teamData.id || !teamData.name) {
+            return undefined;
           }
-        };
-        return mappedAward;
+
+          const mappedAward: PresentationAward = {
```
Comment (johnmeshulam) [inline apps/frontend/src/app/[locale]/lems/(volunteer)/(dashboard)/scorekeeper/components/awards-presentation/awards-presentation-wrapper.tsx]: The common fields in the map should be handled in one place instead of duplicating the entire map function...

at least 50% of it is identical

**Review by johnmeshulam — APPROVED** [review]
